# Generated by Django 4.2.2 on 2023-07-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='actual_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
