# Generated by Django 4.2.2 on 2023-07-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_ad_actual_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='value',
            field=models.BooleanField(default=True),
        ),
    ]
