# Generated by Django 4.2.2 on 2023-07-05 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_username_ad_user_rename_username_bid_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.cat', verbose_name='category'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
